### ISSUE TITLE
Provide project description and README.md file

### ISSUE THREAD

**Issue by ngirard** [renn0xtek9/BookMarkWidgets#1]
Could you please provide a description and a README.md file for your project ?

I'd suggest

- Adding a link to https://www.opendesktop.org/c/1519558653 ;
- Providing compilation instructions
- Specifying that your project currently doesn't work for Firefox nor Chrome

Here are the instructions I used on Ubuntu 18.04 to successfully compile & install your widget:
`sudo apt install extra-cmake-modules plasma-framework-dev qtdeclarative5-dev libkf5iconthemes-dev`
`./install.sh`

Thanks !

**Comment by renn0xtek9** [comment]
Okay done. Thanks for feedback. 
Support for Firefox and Chrome is indeed not yet implemented. I lack time at the moment. 
If you have a bit a programming Knowledge, it should be easily feasible. 
Do you need such features?

**Comment by ngirard** [comment]
Thanks for your responsiveness :-)

What would be useful to me, is to tie a view of a specific folder bookmark to a KDE activity ; but I don't know if you'd consider providing this feature through your app.

**Comment by renn0xtek9** [comment]
You mean you have a file bookmarks.xml that contains FolderA and Folder B, If you are in Activity A you want Folder A to be the root element of the bookmark view, and in Activity B Folder B ? Is it an option to have to separate bookmarks.xml files, one for each activity ?

**Comment by renn0xtek9** [comment]
ngirard. So I ask a Kde Dev. They seem to say that support of activities in plasmoids is rather unstable. Will see what I can. Meanwhile I uploaded version 2.0.1 which has search feature and support for Chrome Bookmarks. (Firefox still missing). I close this issue seems it was related to Readme.md. 
Feel free to open new thread for activity support
